name: deno

on:
  push:
    branches:
      - master

      - main
jobs:
  test:
    name: Test on deno ${{ matrix.deno }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno: [2.x, 1.x]
        # os: [ubuntu-24.04, windows-2022, macOS-latest]
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno --version
      - run: deno test test/deno/*.js --allow-read --allow-write --no-check
