name: node

on:
  push:
    branches:
      - master

      - main
jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20.x, 18.x, 16.x]
        # os: [ubuntu-24.04, windows-2022, macOS-latest]
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
